version: '3'
services:
  v5fox:
    image: dota2/scrapy
    volumes:
      - ../dota2_scrapy:/app
    working_dir: /app/dota2_scrapy
    command: python v5fox_run.py

  igxe:
    image: dota2/scrapy
    volumes:
      - ../dota2_scrapy/:/app
    working_dir: /app/dota2_scrapy
    command: python igxe_run.py

  wybuff:
    image: dota2/scrapy
    volumes:
      - ../dota2_scrapy/:/app
    working_dir: /app/dota2_scrapy
    command: python wybuff_run.py

  c5game:
    image: dota2/scrapy
    volumes:
      - ../dota2_scrapy/:/app
    working_dir: /app/dota2_scrapy
    command: python c5game_run.py